[package]
name = "simple-stock-tracking"
version = "0.1.0"
authors = ["Kanji Tanaka <ktanaka@ichain.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
